branches:
  only:
    - travis
language: cpp
compiler:
  - gcc
before_script:
  - rake build:all --trace
  - ./autogen.sh
  - ./configure --with-libnet-includes=build/include --with-libnet-libraries=build/lib --enable-unittests
script: make
