branches:
  only:
    - travis
language: cpp
compiler:
  - gcc
before_script:
  - rake build:all --trace
  - ./autogen.sh
  - CPPFLAGS="-Ibuild/include" LDFLAGS="-Lbuild/lib/" ./configure --enable-unittests
script: make
